kind: Service
apiVersion: v1
metadata:
  name: spinnaker-demo
  namespace: spinnaker
spec:
  selector:
    source: my-k8s-v2-account
    app: test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
