apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnaker-demo
  namespace: spinnaker
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: index.docker.io/chiamtc/spin-kub-v2-demo
        ports:
        - containerPort: 8000

---

kind: Service
apiVersion: v1
metadata:
  name: spinnaker-demo
  namespace: spinnaker
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
