apiVersion: v1
kind: ConfigMap
metadata:
  name: spinnaker-demo-config
  namespace: spinnaker
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnaker-demo
  namespace: spinnaker
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: index.docker.io/chiamtc/spin-kub-v2-demo
        ports:
        - containerPort: 80
        volumeMounts:
            - mountPath: /opt/config
              name: spinnaker-demo-config
        volumes:
        - configMap:
            name: configmap-v001
          name: spinnaker-demo-config

---

kind: Service
apiVersion: v1
metadata:
  name: spinnaker-demo
  namespace: spinnaker
spec:
  selector:
    source: my-k8s-v2-account
    app: test
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
