apiVersion: v1
kind: Pod                                            
metadata:
  name: sa-frontend2      # The only change
spec:                                                
  containers:
    - image: index.docker.io/chiamtc/spin-kub-v2-demo
      name: sa-frontend                              
      ports:
        - containerPort: 80