apiVersion: v1
kind: Service
metadata:
  name: stage
  namespace: spinnaker
spec:
  selector:
    source: my-k8s-v2-account
    demo: test
  externalIPs: []
  externalTrafficPolicy: Cluster
  loadBalancerSourceRanges: []
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: LoadBalancer


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: stage
  labels:
    source: my-k8s-v2-account
    app: test
spec:
  replicas: 3
  selector:
    matchLabels:
      source: my-k8s-v2-account
      app: test
  template:
    metadata:
      labels:
        source: my-k8s-v2-account
        app: test
    spec:
      containers:
      - image: index.docker.io/chiamtc/spin-kub-v2-demo
        name: spinnaker-stage
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 8000
